# Generated by OmopViewer 0.4.0
# Be careful editing this file

library(bslib)
library(dplyr)
library(DT)
library(gt)
library(markdown)
library(omopgenerics)
library(OmopSketch)
library(plotly)
library(purrr)
library(readr)
library(rlang)
library(shiny)
library(shinycssloaders)
library(shinyWidgets)
library(sortable)
library(tidyr)
library(visOmopResults)
library(yaml)

# preprocess data if it has not been done
fileData <- file.path(getwd(), "data", "shinyData.RData")
# if (!file.exists(fileData)) {
#   source(file.path(getwd(), "data", "preprocess.R"))
# }

# uncomment to load the raw data
# rawData <- omopgenerics::importSummarisedResult(file.path(getwd(), "data"))

# load shiny data
load(fileData)

#saveRDS(data, here::here("data", "results.rds"), compress = "xz")
filerds <- file.path(getwd(), "data", "results.rds")

vocabVersion <- readRDS(file = file.path(getwd(), "data", "vocab_version.rds"))

options(shiny.timeout = 300) 
options(shiny.maxRequestSize = 100 * 1024^2)  # 100MB

# source functions
source(file.path(getwd(), "functions.R"))
