# Generated by OmopViewer 0.4.0
# Be careful editing this file

server <- function(input, output, session) {
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(fileName = file)
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_concept_id_counts = FALSE
  )

  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_omop_snapshot_cdm_name,
    {
      updateButtons$summarise_omop_snapshot <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_omop_snapshot_variable_name,
    {
      updateButtons$summarise_omop_snapshot <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )
  # summarise_concept_id_counts -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_concept_id_counts_cdm_name,
    {
      updateButtons$summarise_concept_id_counts <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_concept_id_counts_omop_table,
    {
      updateButtons$summarise_concept_id_counts <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_concept_id_counts_age_group,
    {
      updateButtons$summarise_concept_id_counts <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_concept_id_counts_sex,
    {
      updateButtons$summarise_concept_id_counts <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_concept_id_counts_time_interval,
    {
      updateButtons$summarise_concept_id_counts <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_concept_id_counts_estimate_name,
    {
      updateButtons$summarise_concept_id_counts <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_concept_id_counts_study_period_end,
    {
      updateButtons$summarise_concept_id_counts <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_concept_id_counts_study_period_start,
    {
      updateButtons$summarise_concept_id_counts <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_concept_id_counts, {
    if (updateButtons$summarise_concept_id_counts == TRUE) {
      output$update_message_summarise_concept_id_counts <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_concept_id_counts <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_concept_id_counts, {
    updateButtons$summarise_concept_id_counts <- FALSE
  })

  ## get summarise_concept_id_counts data
  getSummariseConceptIdCountsData <- shiny::eventReactive(input$update_summarise_concept_id_counts, {
    data[["summarise_concept_id_counts"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_concept_id_counts_cdm_name,
        .data$estimate_name %in% input$summarise_concept_id_counts_estimate_name
      ) |>
      omopgenerics::filterGroup(.data$omop_table %in% input$summarise_concept_id_counts_omop_table) |>
      omopgenerics::filterStrata(
        .data$age_group %in% input$summarise_concept_id_counts_age_group,
        .data$sex %in% input$summarise_concept_id_counts_sex
      ) |>
      omopgenerics::filterAdditional(.data$time_interval %in% input$summarise_concept_id_counts_time_interval) 
      
  })
  
  getSummariseConceptIdCountsTable <- shiny::reactive({
    getSummariseConceptIdCountsData() |>
      OmopSketch::tableConceptIdCounts(type = "reactable", display = input$summarise_concept_id_counts_display)
  })
  output$summarise_concept_id_counts_table <- reactable::renderReactable({
    getSummariseConceptIdCountsTable()
  })
  output$summarise_concept_id_counts_table_download <- shiny::downloadHandler(
    filename = "summarise_concept_id_counts.csv",
    content = function(file) {
      data <- getSummariseConceptIdCountsData()
      utils::write.csv(data, file, row.names = FALSE)
    }
  )
  
  getTopConceptsTable <- shiny::reactive({
    getSummariseConceptIdCountsData() |>
      OmopSketch::tableTopConceptCounts(type = "gt", top = as.numeric(input$top_concepts_top))
  })
  output$top_concepts_table <- gt::render_gt({
    getTopConceptsTable()
  })
  output$top_concepts_table_download <- shiny::downloadHandler(
    filename = paste0("top_concept_counts_table.", input$top_concepts_table_format),
    content = function(file) {
      gt::gtsave(getTopConceptsTable(), file)
    }
  )
  
  
  
  
}
