# Generated by OmopViewer 0.4.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "hdruk_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(bootswatch = "flatly"),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Snapshot",
    icon = shiny::icon("camera"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        shinyWidgets::pickerInput(
          inputId = "summarise_omop_snapshot_cdm_name",
          label = "CDM name",
          choices = choices$summarise_omop_snapshot_cdm_name,
          selected = selected$summarise_omop_snapshot_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_omop_snapshot_variable_name",
          label = "Variable name",
          choices = choices$summarise_omop_snapshot_variable_name,
          selected = selected$summarise_omop_snapshot_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      shiny::actionButton(
        inputId = "update_summarise_omop_snapshot",
        label = "Update content",
        width = "200px"
      ),
      shiny::div(shiny::textOutput(outputId = "update_message_summarise_omop_snapshot"), class = "ov_update_button"),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table Snapshot",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_omop_snapshot_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            gt::gt_output("summarise_omop_snapshot_table") |>
              shinycssloaders::withSpinner()
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Concept Counts",
    icon = shiny::icon("calculator"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        shinyWidgets::pickerInput(
          inputId = "summarise_concept_id_counts_cdm_name",
          label = "CDM name",
          choices = choices$summarise_concept_id_counts_cdm_name,
          selected = selected$summarise_concept_id_counts_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_concept_id_counts_omop_table",
          label = "Omop table",
          choices = choices$summarise_concept_id_counts_omop_table,
          selected = selected$summarise_concept_id_counts_omop_table,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_concept_id_counts_age_group",
          label = "Age group",
          choices = choices$summarise_concept_id_counts_age_group,
          selected = "overall",
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_concept_id_counts_time_interval",
          label = "Time interval",
          choices = choices$summarise_concept_id_counts_time_interval,
          selected = "overall",
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_concept_id_counts_estimate_name",
          label = "Estimate name",
          choices = choices$summarise_concept_id_counts_estimate_name,
          selected = selected$summarise_concept_id_counts_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      shiny::actionButton(
        inputId = "update_summarise_concept_id_counts",
        label = "Update content",
        width = "200px"
      ),
      shiny::div(shiny::textOutput(outputId = "update_message_summarise_concept_id_counts"), class = "ov_update_button"),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_concept_id_counts_table_format",
                  label = "Format",
                  choices = c("csv"),
                  selected = "csv",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_concept_id_counts_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_concept_id_counts_display",
                  label = "Display",
                  choices = c("overall", "standard", "source", "missing standard", "missing source"),
                  selected = "overall",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              reactable::reactableOutput("summarise_concept_id_counts_table") |>
                shinycssloaders::withSpinner()
            )
          )
        ), 
        bslib::nav_panel(
          title = "Top Concepts",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "top_concepts_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "top_concepts_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "top_concepts_top",
                  label = "Top",
                  choices = c(5, 10, 25, 50, 100),
                  selected = 10,
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              gt::gt_output("top_concepts_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.4.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
