
# Generated by OmopViewer 0.2.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "hdruk_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(bootswatch = "flatly"), # cerulean
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("disease"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Snapshot",
    icon = shiny::icon("camera"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Grouping",
            shinyWidgets::pickerInput(
              inputId = "summarise_omop_snapshot_grouping_cdm_name",
              label = "Cdm name",
              choices = filterValues$summarise_omop_snapshot_grouping_cdm_name,
              selected = filterValues$summarise_omop_snapshot_grouping_cdm_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Variables",
            shinyWidgets::pickerInput(
              inputId = "summarise_omop_snapshot_variable_name",
              label = "Variable name",
              choices = filterValues$summarise_omop_snapshot_variable_name,
              selected = filterValues$summarise_omop_snapshot_variable_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          ),
          bslib::accordion_panel(
            title = "Estimates",
            shinyWidgets::pickerInput(
              inputId = "summarise_omop_snapshot_estimate_name",
              label = "Estimate name",
              choices = filterValues$summarise_omop_snapshot_estimate_name,
              selected = filterValues$summarise_omop_snapshot_estimate_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Formatted",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_omop_snapshot_gt_17_download_type",
                  label = "File type",
                  selected = "docx",
                  choices = c("docx", "png", "pdf", "html"),
                  multiple = FALSE
                ),
                shiny::downloadButton(outputId = "summarise_omop_snapshot_gt_17_download", label = "Download")
              ),
              class = "text-end"
            ),
            gt::gt_output("summarise_omop_snapshot_gt_17") |>
              shinycssloaders::withSpinner()
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    icon = shiny::icon("calculator"),
    title = "Concept_id counts",
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        bslib::accordion(
          bslib::accordion_panel(
            title = "Grouping",
            shinyWidgets::pickerInput(
              inputId = "summarise_concept_id_counts_grouping_cdm_name",
              label = "Cdm name",
              choices = filterValues$summarise_concept_id_counts_grouping_cdm_name,
              selected = filterValues$summarise_concept_id_counts_grouping_cdm_name,
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_concept_id_counts_grouping_omop_table",
              label = "Omop table",
              choices = filterValues$summarise_concept_id_counts_grouping_omop_table,
              selected = c("drug_exposure"),
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_concept_id_counts_grouping_age_group",
              label = "Age group",
              choices = filterValues$summarise_concept_id_counts_grouping_age_group,
              selected = "overall",
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_concept_id_counts_grouping_sex",
              label = "Sex",
              choices = filterValues$summarise_concept_id_counts_grouping_sex,
              selected = "overall",
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            ),
            shinyWidgets::pickerInput(
              inputId = "summarise_concept_id_counts_grouping_interval",
              label = "Year",
              choices = filterValues$summarise_concept_id_counts_grouping_interval,
              selected = "overall",
              multiple = TRUE,
              options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
            )
          )
        )
      ),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_concept_id_counts_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            DT::dataTableOutput("summarise_concept_id_counts_tidy") |>
              shinycssloaders::withSpinner()
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.2.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
